<div class="pro-main">
	<h2 class="centered">We are launching Pro Version in a month</h2>
        <center><a target="_blank" class="lv_pro_banner" href="https://wisetr.com/gravity-forms-addons/?utm_source=wp_free_plugin&utm_medium=free_plugin_banner&utm_term=pro_launch&utm_content=pro_banner_link&utm_campaign=free_plugin"><img src="<?php echo LV_ROOT_URL."admin/assets/img/pro-banner.png"; ?>" width="819" height="320"/></a></center>
    
    <div class="pro-questions">
    	<ol>
             <li>
        	<div class="question"><i class="fa fa-hand-o-right" aria-hidden="true"></i> What are the advanced set of feartures?</div>
            <div class="answer">We are working to launch some new set of fields which will enhance the overall functioanlity of Gravity Forms. These fields will have advanced options to enable even more validation criterias. Custom skins will be launched to enhance the overall User experience.</div>
        </li>
        <li>
        	<div class="question"><i class="fa fa-hand-o-right" aria-hidden="true"></i> What is the ETA to launch?</div>
            <div class="answer">We are burning a lot of midnight oil and also emptying mugs of coffee fast. The work is on track and we are slated for our official launch in less than a month. Watch out this space.</div>
        </li>
        
        
          <li>
        	<div class="question"><i class="fa fa-hand-o-right" aria-hidden="true"></i> Who is the team behind it?</div>
                <div class="answer">Great question. We are <a href="https://wisetr.com/gravity-forms-addons/?utm_source=wp_free_plugin&utm_medium=free_plugin_faq_link&utm_term=pro_launch&utm_content=pro_faq_link&utm_campaign=free_plugin" target="_blank">Wisetr</a>. A WordPress development consultancy for your growing small business. People come to us for everything WordPress- small tweaks to bespoke applications.</div>
        </li>
        
        
          <li>
        	<div class="question"><i class="fa fa-hand-o-right" aria-hidden="true"></i> What is your motivation behind the plugin?</div>
            <div class="answer">We are so glad you asked. We were hit by a bolt from the blue in form of a loan lending company. While re-developing their website, we figured out they had a form which was drab as hell and running into 3 pages. People who could complete it had a serious level of commitment and some form of eternal love. 
We built live validation for them on top of their existing gravity form. And boom! As expected, the conversion rate skyrocketed. We knew we had to take this to the world. Our first pit stop is the WordPress repo.</div>
        </li>
        
         
          <li>
        	<div class="question"><i class="fa fa-hand-o-right" aria-hidden="true"></i> How can I know when the plugin launched?</div>
            <div class="answer" style="border:none;">Simply enter your Email below & we will keep you posted. </div>
        </li>
        
        
        </ol>
    </div>
    
    
    <div class="signup-pro">
    <center><h3>Signup Now to Send your Access Request for Pro Version to Team Wisetr. </h3></center>
    	<form method="post">
        		<div class="inputfield"> <input type="hidden" name="action" value="lv_pro_subscribe"><input type="text" name="email" placeholder="Enter Your Email ID"/> <input type="submit" value="Signup Now" /></div>
        </form>
    </div>
    
	<div class="wisetrfooter"><img align="absmiddle" src="<?php echo LV_ROOT_URL."admin/assets/img/logo_wisetr.png"; ?>" /> Supported by Wisetr Team of WordPress Experts</div>
    	


</div>